### ISSUE TITLE
LNURL

### ISSUE THREAD

**Issue by thefeli73** [getumbrel/umbrel-lightning#17]
apart from invoice links there is nowhere to paste LNURL links, eg for connecting to nodes. lnbig(dot)com, for example, currently only lets you connect to a channel with a LNURL link, making it impossible to get inbound liquidity from lnbig with umbrel (or RTL, they dont have that feature either)

**Comment by jimbrend** [comment]
Old thread, feel free to re-open as well if you want to discuss any latest wallets with LNURL (or too if you want to chat about BOLT12)
​
LNBits has a great LNURL solution! https://apps.umbrel.com/app/lnbits
​
LNURL-pay extension can make LNURLp re-usable links where you can specify a range for LNbits, any LNURL wallet like wallet of satoshi can make these too, or nutstash's cashu ecash tokens also does this with reusable addresses,
​
For the lightning address apps currently it seems support is only with BTCPay, LNbits, Phoenix, ThunderHub, Zap (no longer being officially supported), & Zeus allow lightning node connection and receiving via LNURL addresses in our ecosystem,
​
Feel free to, if you discover any other information or anyone ever has any other questions reach out at https://www.umbrel.com/support
