### ISSUE TITLE
change port 8080 for lnd 

### ISSUE THREAD

**Issue by thefeli73** [getumbrel/umbrel-lightning#18]
port 8080 is commonly used by other software. This can easily changed in the configure script (as i have done in the past) but updating Umbrel seems to reset this and write the 8080 port everywhere making it extremely annoying to fix.
I suggest chaning the port from 8080 -> 8448 or something that just isn't used as frequently

**Comment by jimbrend** [comment]
We have a workaround to change upon a [first installation](https://github.com/getumbrel/umbrel/issues/1576#issuecomment-1380281168)... or something along those lines... aware on this one and will keep top of mind going forward... 
Closing for now
