### ISSUE TITLE
For new users, starting a lightning channel is difficult and ineffective

### ISSUE THREAD

**Issue by MickMorucci** [getumbrel/umbrel-lightning#19]
**User Problem:**
- As a new lightning channel user, I don't know **which** channels I should connect to,
- As a new lightning channel user, I don't know which channels are better & most profitable/effective to connect to.
- As a new lightning channel user, I fail to connect to the majority of lightning addresses.
  
**Suggestions:**
- How may we use software to help new lightning users set-up optimal channels. These may be channels that have most active and recurring transactions.
   - Story: User trying to open a lightning channel is provided a list of options of channels to connect to.

**Comment by jimbrend** [comment]
Old thread when we were still early! 

A beginner guide:
https://community.umbrel.com/t/managing-liquidity-and-lightning-node-basics/12940


More communities, and ancillary resources to learn more about lightning!

https://river.com/learn/files/river-lightning-report-2023.pdf
https://t.me/plebnet/205345
https://github.com/lnbook/lnbook (this is Mastering the Lightning Network on Github)
https://medium.com/@wbobeirne/making-a-lightning-web-app-part-1-4a13c82f3f78
https://www.udemy.com/course/pleblabaustin/
https://zebedee.io/
https://github.com/getumbrel/umbrel-apps (for packaging an app for Umbrel at the bottom)
https://twitter.com/kodylow/status/1681779247093022721?s=20
https://docs.strike.me/
https://github.com/neb-b/dono.at
https://lnbits.com/
https://github.com/SamSamskies/PlebPay
https://t.me/thunderhub
https://lightningcommunity.slack.com/archives/C6BKD3RKR 
https://t.me/plebnet 
https://www.reddit.com/r/lightningnetwork/
https://github.com/MutinyWallet
https://lightningaddress.com/
https://github.com/andrerfneves/lightning-address/blob/master/README.md#wallets-supported
https://t.me/fedibtc
https://keet.io/


Feel free to re-open if you had a question!

Closing!
