### ISSUE TITLE
Recovering a wallet 

### ISSUE THREAD

**Issue by nbourbon** [getumbrel/umbrel-lightning#2]
I found to my surprise that after having to restart my node from scratch in latest umbrel versions I can’t use my seedphrase to restart my wallet. 
it only creates a new one and in telegram they suggested I need to use an older version? Or to follow some advanced processes now to recover my funds from my openness channels

I find it very risky to recommend umbrel (despite of how much I line it) if there is no way to use my seedphrase directly. Is this something you can fix?

**Comment by louneskmt** [comment]
Hey! Please check this out: https://github.com/getumbrel/umbrel/issues/1461#issuecomment-1171479992.

**Comment by nbourbon** [comment]
thanks, I restored it manually with those backups... but I hope this comes in the UI ASAP as many many umbrel users would have no clue on how to restore and follow up on these steps.

**Comment by nevets963** [comment]
Hi @nbourbon The latest version of the lightning app added automatic channel recovery. See here: https://twitter.com/umbrel/status/1562099972547690501
