### ISSUE TITLE
Umbrel doesn't show On Chain balance after restore

### ISSUE THREAD

**Issue by souspeed** [getumbrel/umbrel-lightning#20]
After standard restore procedure on Umbrel, only the lightning balances from the closed channels appear in Umbrel.

Umbrel does show the starting onchain balance 'deposit', however this whole balance is listed as 'lightning wallet - channel open', even when only part of this balance is used the open the channel. The remaining part is still in the onchain wallet.
After restore and closing the channels, only the closed channel amount shows up in Umbrel 'deposit'. However; the remaining onchain balance remains in limbo. 

I did perform the UTXO rescan procedure, but onchain balance didn't show.

Might be I did not wait long enough? 20+ hours after electrum finished indexing. 
Still I think this should be analysed/improved, as more and more 'beginners' will run into this issue.

Blue wallet did show the full balance within minutes. 
Maybe worth to check their process and mimic this logic on Umbrel for restore/re-scan purposes.

-------------------------------
- Standard restore procedure:
- This method is the normal way, as described and recommended by Umbrel team.
- 
- It is suppose that you already have the 24 words seed and the channel.backup file obtained previously. If you didn’t make that backup, but you still have access to your old node drive, you can find it in /home/umbrel/umbrel/lnd/data/chain/bitcoin/mainnet/channel.backup or you can request a copy from Umbrel devs.
- 
- Install a new instance of Umbrel. Start the dashboard page and you will be prompted to use previously backup 24 words seed.
- 
- Once you’ve restored from the 24 words, it might take a few minutes to a few hours for it to scan all of your previous Bitcoin (on-chain) transactions and balances. Meanwhile, here’s how you can restore the funds in your Lightning channels.
- 
- STEP 1: COPY OVER THE CHANNEL BACKUP FILE FROM YOUR COMPUTER TO YOUR UMBREL.
- 
- Enter using SSH 28 and run this:
- 
- scp <path/to/your/channel/backup/file> umbrel@umbrel.local:/home/umbrel/umbrel/lnd/channel.backup
- 
- Replace <path/to/your/channel/backup/file> with the exact path to channel backup file on your computer
- The password is moneyprintergobrrr, except on version 0.3.3 or later where the password is your personal user password instead.
- 
- STEP 2: RECOVER FUNDS
- 
- cd ~/umbrel && ./bin/lncli restorechanbackup --multi_file /data/.lnd/channel.backup
-
- After you run this, wait for 1 minute. You should now be able to see your channels being closed on http://umbrel.local/lightning 7.
- You should wait patiently until the funds are coming back to your onchain wallet. It will take at least 40 blocks. You can see/check the details of closing channels in the troubleshooting guide.

------------------------------
- Extra Step to show full balance after channel closes.
- Enter seed into Blue Wallet mobile wallet.
------------------------------

- Rescan wallet UTXOs procedure
- 
- I sent funds to my node wallet and wasn’t 100% synced, now I can’t see them.
- 
- Step 1 – In a terminal window, execute this to SSH:
- 
- ssh -t umbrel@umbrel.local
- 
- Password: < your own dashboard password > (remember that you will not see what you type, then press ENTER)
- 
- Step 2 – execute the following command to rescan wallet’s UTXOs:
- 
- sed -i "s/\[Application Options\]/\[Application Options\]\nreset-wallet-transactions=true/g;" ~/umbrel/lnd/lnd.conf && sudo reboot
- 
- Step 3 – Wait some time so LND can rescan all wallet’s UTXOs. If it solve the issue, run this to stop it from rescanning on a future restart:
- 
- sed -i "s/reset-wallet-transactions=true//g;" ~/umbrel/lnd/lnd.conf && sudo reboot
- 
- Wait, it can take quite a while.

------------------------------

Guides
https://community.getumbrel.com/t/how-to-restore-your-node-wallet/3602
https://bitcoin.cipix.eu/en/umbrel-troubleshooting/#umbrel-rescan-utxo

**Comment by jimbrend** [comment]
Hi!  

Lots of people here!  

Also, lots of funds being secured onchain... many new channels being opened!   Update to latest version!  Make sure to secure funds to avoid a [disaster recovery](https://docs.lightning.engineering/lightning-network-tools/lnd/disaster-recovery) or we can troubleshoot any current setups to get them up and running again, and since the last date on this issue we added an [Automated Recovery](https://twitter.com/umbrel/status/1562099972547690501) feature for SCB backups!  

We're streamlining these processes and helping make them easier, feel free to reach out to https://www.umbrel.com/support if anyone has not been able to yet recover for currently recommended steps,

We can assist 1:1 there!  

Closing outdated thread
