### ISSUE TITLE
QR generator codes are not recognized by Android Lightning wallets

### ISSUE THREAD

**Issue by andrasfuchs** [getumbrel/umbrel-lightning#25]
I have just tried to receive some satoshis on my Umbrel v0.4.1 using the invoice QR code generator on the Lightning tab.
I tried to paste it with Muun, Breez and Phoenix on Android, but all of them failed to recognize it.

Does anyone else have the same experience? 

I also tried to paste the text code below the QR code into all those clients, and it worked fine with all of them.

**Comment by jimbrend** [comment]
Generally there may be routing errors if no liquidity, other factors on what invoice scanned, and connection issues depending on wallet 

Feel free to re-open if you'd like to chat on your current use-case
