### ISSUE TITLE
[Issue] Send Max Balance is not sending all balance

### ISSUE THREAD

**Issue by Darth-Coin** [getumbrel/umbrel-lightning#28]
I made a test using 3 types/apps to make a tx onchain with Umbrel wallet.
To send Max Balance in 1 tx to an external BTC address, using medium fee.

Test A - Umbrel interface is NOT sending all balance
- 3 UTXOs with a total of 3M sats
- using Umbrel dashboard Bitcoin, select max balance, select custom fee 3sat/vB
- is sending only 2.1M sats and remain 90k sats in Umbrel wallet

Test B - RTL app
- 3 UTXOs with a total of 3M sats
- Onchain, select all balance, select 2sats/vB
- is sending ALL balance, remaining 0 sats in Umbrel wallet

Test C - Bluewallet (imported seed)
- 3 UTXOs with a total of 3M sats
- Send - coin control - select "max" all balance
- is sending ALL balance, remaining 0 sats in Umbrel wallet

The main dashboard Umbrel have issues managing UTXOs, please revise.

**Comment by RaulRider** [comment]
I guess that the issue with wrong UTXO by umbrel dashboard is the same as in here: getumbrel/umbrel-lightning#20

recovering in Blue Wallet (using umbrel's 24 words seed) gives right UTXOs and addresses
it migh be realte to issues with electrs?

**Comment by jimbrend** [comment]
This is unrelated to #20 and recovery, 

And should have been resolved after updating past LND 0.14, navigate to your App Store > Updates and make sure you're on the latest versions as also recommended by Lightning Labs to stay updated!

Feel free to reping if anyone has any issue!
