### ISSUE TITLE
Rename Lightning address to avoid confusion with LNURL Lightning Addresses

### ISSUE THREAD

**Issue by fanismichalakis** [getumbrel/umbrel-lightning#3]
The node address is currently referred to as "Lightning address" in the UI of the Lightning app, which may cause confusion with LNURL-based Lightning Addresses. Although the name "Lightning address" was in use in Umbrel's dashboard before the LNURL LN addresses caught traction, their usage is now quite widespread, and the term "Lightning Address" is strongly associated with LNURL Lightning Addresses.

The worst case scenario is a newcomer thinking their node address is a LNURL Lightning Address and pasting it on Twitter or Reddit, thus potentially harming their privacy as it would tie their UTXOs to their social media account.

The best name remains up to discussion. I think something like "Node Address" works very well, as it is already clear from context that it is Lightning related stuff. Just "Address" (as in Amboss) works too.

**Comment by mayankchhabra** [comment]
Thanks for the great suggestion. Totally agree with the reasoning. We'll rename it to "Node ID" in the next update.

**Comment by mayankchhabra** [comment]
Done in yesterday's release. :)
Thanks @fanismichalakis!
