### ISSUE TITLE
Error: Invalid seed length

### ISSUE THREAD

**Issue by rorp** [getumbrel/umbrel-lightning#31]
I keep getting this error message on `http://umbrel-dev.local` after fresh `umbrel-dev` installation. After that the spinner spins indefinitely.

Steps to reproduce

1. run `umbrel-dev init`
2. run `umbrel-dev boot`
3. go to `http://umbrel-dev.local` in your browser
4. enter your name and password
5. on `note down your secret words` screen click `NOTE DOWN LATER`

Expected result: the next screen shows up.

Actual result: `Error: Invalid seed length` message shows up and the next screen doesn't.

**Comment by jimbrend** [comment]
these look to be confirmed as permission issues related to previous custom Linux installs and older versions, 

Solution looks to be we should have secured funds on any old machines and also can just update to the new umbrelOS! 

Closing, feel free to re-open if there was still an issue
