### ISSUE TITLE
 Lightning Node: Connect your Lightning wallet to your node

### ISSUE THREAD

**Issue by TZocker** [getumbrel/umbrel-lightning#39]
Position:
Lightning Node: Connect your Lightning wallet to your node

I have a Problem to scan the rest QR Code with my Monitor with the Zeus app.

Solve:
STRG + 

Possible fix:

Slider

Thx

**Comment by jimbrend** [comment]
been testing the resolutions/zooming in here with Control + or Command + on View with various monitors, which was the resolution here to zoom in further, 

testing on various monitors and looking to optimize further, thank you for your feedback
