### ISSUE TITLE
Unable to close channels: "Unable to close channel, server is still in the process of starting" error

### ISSUE THREAD

**Issue by kirillzh** [getumbrel/umbrel-lightning#7]
After updating to 0.5.2, no longer able to close LN channels.

<img width="363" alt="Screenshot 2022-11-24 at 4 10 52 PM" src="https://user-images.githubusercontent.com/5660531/203876817-eef28abf-35ac-40e7-b284-9b7ce606845e.png">

**Comment by mayankchhabra** [comment]
Hey @kirillzh, this should only happen when the Lightning Node app is still starting. Does the issue still persist for you?

**Comment by jimbrend** [comment]
Hey @kirillzh if this wasn't resolved feel free to re-open and ping me 

Or hop over to https://www.umbrel.com/support to see all of our avenues of support and reach out on your preferred one, 

Can e-mail or also hop into the telegram to post any log if you were still running into any issues, don't hesitate to reach out!

Closing for now
