### ISSUE TITLE
UI when switching to BTC unit the SATS are not converted to BTC

### ISSUE THREAD

**Issue by tobakk** [getumbrel/umbrel-lightning#8]
I was playing around with the wallet and realized when you receive a few sats then switch display unit to BTC the amount of sats received is not updated.

See screenshot. I did only reccieve 100 Sats but it says 100 BTC instead.

**Comment by tobakk** [comment]
![Screenshot 2022-12-08 at 13 01 53](https://user-images.githubusercontent.com/17847628/206442672-c286a315-9699-4077-a60c-531644b43b19.png)

**Comment by mayankchhabra** [comment]
Great eye, thank you for the bug report. We'll fix it in the next release!

**Comment by nmfretz** [comment]
Thanks again @tobakk. This has now been fixed d7feeb0b1a5cb440dfe84225dd226d76c5ce3826
